// ============================================================
// Centralized Mock Data — Single Source of Truth
// All pages import from here to ensure consistency
// ============================================================

// ---- CUSTOMERS ----
export const customers = [
  {
    id: "CUS-001",
    name: "John Smith",
    initials: "JS",
    email: "john.smith@example.com",
    phone: "(512) 555-0101",
    address: "123 Main St, Austin, TX 78701",
    joinDate: "2025-06-15",
    totalSpent: 18500,
    totalRequests: 5,
    rating: 4.9,
    status: "active" as const,
  },
  {
    id: "CUS-002",
    name: "Sarah Johnson",
    initials: "SJ",
    email: "sarah.j@example.com",
    phone: "(512) 555-0102",
    address: "456 Oak Ave, Austin, TX 78702",
    joinDate: "2025-08-22",
    totalSpent: 7200,
    totalRequests: 3,
    rating: 4.8,
    status: "active" as const,
  },
  {
    id: "CUS-003",
    name: "Robert Davis",
    initials: "RD",
    email: "robert.d@example.com",
    phone: "(512) 555-0103",
    address: "789 Pine Rd, Austin, TX 78703",
    joinDate: "2025-09-10",
    totalSpent: 2850,
    totalRequests: 2,
    rating: 4.7,
    status: "active" as const,
  },
  {
    id: "CUS-004",
    name: "Emily Chen",
    initials: "EC",
    email: "emily.c@example.com",
    phone: "(512) 555-0104",
    address: "321 Elm St, Austin, TX 78704",
    joinDate: "2025-11-05",
    totalSpent: 2200,
    totalRequests: 1,
    rating: 5.0,
    status: "active" as const,
  },
  {
    id: "CUS-005",
    name: "Michael Brown",
    initials: "MB",
    email: "michael.b@example.com",
    phone: "(512) 555-0105",
    address: "654 Cedar Ln, Austin, TX 78705",
    joinDate: "2025-12-01",
    totalSpent: 4500,
    totalRequests: 2,
    rating: 4.6,
    status: "active" as const,
  },
  {
    id: "CUS-006",
    name: "Lisa Anderson",
    initials: "LA",
    email: "lisa.a@example.com",
    phone: "(512) 555-0106",
    address: "987 Cedar Ln, Austin, TX 78706",
    joinDate: "2026-01-12",
    totalSpent: 500,
    totalRequests: 1,
    rating: 4.5,
    status: "active" as const,
  },
]

// ---- TECHNICIANS ----
export const technicians = [
  {
    id: "TECH-001",
    name: "Mike Wilson",
    initials: "MW",
    email: "mike.w@omis.com",
    phone: "(512) 555-0201",
    address: "Austin, TX",
    specialization: "Solar Installation",
    specializations: ["Solar Installation", "Electrical Panels"],
    certifications: ["NABCEP PV", "Master Electrician"],
    rating: 4.9,
    completedJobs: 156,
    activeJobs: 2,
    status: "available" as const,
    joinDate: "2023-03-15",
    earnings: 145000,
    avatar: null as string | null,
  },
  {
    id: "TECH-002",
    name: "James Brown",
    initials: "JB",
    email: "james.b@omis.com",
    phone: "(512) 555-0202",
    address: "Austin, TX",
    specialization: "Emergency Repairs",
    specializations: ["Emergency Repairs", "Commercial Electrical"],
    certifications: ["Journeyman Electrician", "OSHA 30"],
    rating: 4.7,
    completedJobs: 89,
    activeJobs: 3,
    status: "on_job" as const,
    joinDate: "2023-08-20",
    earnings: 98000,
    avatar: null as string | null,
  },
  {
    id: "TECH-003",
    name: "Tom Harris",
    initials: "TH",
    email: "tom.h@omis.com",
    phone: "(512) 555-0203",
    address: "Round Rock, TX",
    specialization: "EV Chargers",
    specializations: ["Residential Wiring", "EV Chargers"],
    certifications: ["Master Electrician", "EV Certified"],
    rating: 4.8,
    completedJobs: 67,
    activeJobs: 1,
    status: "available" as const,
    joinDate: "2024-01-10",
    earnings: 72000,
    avatar: null as string | null,
  },
  {
    id: "TECH-004",
    name: "David Lee",
    initials: "DL",
    email: "david.l@omis.com",
    phone: "(512) 555-0204",
    address: "Cedar Park, TX",
    specialization: "Residential Wiring",
    specializations: ["Solar Maintenance", "Inspections"],
    certifications: ["Journeyman Electrician"],
    rating: 4.6,
    completedJobs: 45,
    activeJobs: 2,
    status: "available" as const,
    joinDate: "2024-06-01",
    earnings: 52000,
    avatar: null as string | null,
  },
  {
    id: "TECH-005",
    name: "Carlos Martinez",
    initials: "CM",
    email: "carlos.m@omis.com",
    phone: "(512) 555-0205",
    address: "Pflugerville, TX",
    specialization: "Commercial Electrical",
    specializations: ["Commercial Solar", "Panel Upgrades"],
    certifications: ["Master Electrician", "OSHA 30"],
    rating: 4.9,
    completedJobs: 34,
    activeJobs: 0,
    status: "off_duty" as const,
    joinDate: "2024-09-15",
    earnings: 41000,
    avatar: null as string | null,
  },
  {
    id: "TECH-006",
    name: "Sarah Williams",
    initials: "SW",
    email: "sarah.w@omis.com",
    phone: "(512) 555-0206",
    address: "Austin, TX",
    specialization: "Panel Upgrades",
    specializations: ["Panel Upgrades", "Residential Electrical"],
    certifications: ["Journeyman Electrician", "NABCEP PV"],
    rating: 4.8,
    completedJobs: 21,
    activeJobs: 1,
    status: "on_job" as const,
    joinDate: "2025-02-01",
    earnings: 28000,
    avatar: null as string | null,
  },
]

// ---- SERVICE REQUESTS ----
export type RequestStatus = "pending" | "quoted" | "in_progress" | "scheduled" | "completed" | "cancelled"

export const serviceRequests = [
  {
    id: "REQ-001",
    customerId: "CUS-001",
    customer: "John Smith",
    customerEmail: "john.smith@example.com",
    customerPhone: "(512) 555-0101",
    customerInitials: "JS",
    service: "Solar Panel Installation",
    description: "Complete rooftop solar panel installation for a 2,500 sq ft home. 20-panel system with inverter and monitoring.",
    address: "123 Main St, Austin, TX 78701",
    status: "in_progress" as RequestStatus,
    priority: "high" as const,
    assignedTech: "Mike Wilson",
    techId: "TECH-001",
    estimatedCost: 15000,
    createdAt: "2026-02-20",
    scheduledDate: "2026-03-05",
    urgency: "MEDIUM",
  },
  {
    id: "REQ-002",
    customerId: "CUS-002",
    customer: "Sarah Johnson",
    customerEmail: "sarah.j@example.com",
    customerPhone: "(512) 555-0102",
    customerInitials: "SJ",
    service: "Electrical Panel Upgrade",
    description: "Upgrade electrical panel from 100A to 200A to support new appliances and EV charger.",
    address: "456 Oak Ave, Austin, TX 78702",
    status: "in_progress" as RequestStatus,
    priority: "medium" as const,
    assignedTech: "Mike Wilson",
    techId: "TECH-001",
    estimatedCost: 3500,
    createdAt: "2026-02-22",
    scheduledDate: "2026-03-08",
    urgency: "MEDIUM",
  },
  {
    id: "REQ-003",
    customerId: "CUS-003",
    customer: "Robert Davis",
    customerEmail: "robert.d@example.com",
    customerPhone: "(512) 555-0103",
    customerInitials: "RD",
    service: "Emergency Repair",
    description: "Electrical short circuit causing power outage in main floor. Needs immediate attention.",
    address: "789 Pine Rd, Austin, TX 78703",
    status: "completed" as RequestStatus,
    priority: "urgent" as const,
    assignedTech: "James Brown",
    techId: "TECH-002",
    estimatedCost: 850,
    createdAt: "2026-02-15",
    scheduledDate: "2026-02-15",
    urgency: "HIGH",
  },
  {
    id: "REQ-004",
    customerId: "CUS-004",
    customer: "Emily Chen",
    customerEmail: "emily.c@example.com",
    customerPhone: "(512) 555-0104",
    customerInitials: "EC",
    service: "EV Charger Installation",
    description: "Level 2 EV charger installation in garage. Requires new 240V circuit from panel.",
    address: "321 Elm St, Austin, TX 78704",
    status: "quoted" as RequestStatus,
    priority: "low" as const,
    assignedTech: "Tom Harris",
    techId: "TECH-003",
    estimatedCost: 2200,
    createdAt: "2026-02-25",
    scheduledDate: null,
    urgency: "LOW",
  },
  {
    id: "REQ-005",
    customerId: "CUS-005",
    customer: "Michael Brown",
    customerEmail: "michael.b@example.com",
    customerPhone: "(512) 555-0105",
    customerInitials: "MB",
    service: "Residential Wiring",
    description: "Complete garage rewiring with dedicated circuits for workshop equipment.",
    address: "654 Cedar Ln, Austin, TX 78705",
    status: "scheduled" as RequestStatus,
    priority: "medium" as const,
    assignedTech: "Tom Harris",
    techId: "TECH-003",
    estimatedCost: 4500,
    createdAt: "2026-02-18",
    scheduledDate: "2026-03-10",
    urgency: "MEDIUM",
  },
  {
    id: "REQ-006",
    customerId: "CUS-006",
    customer: "Lisa Anderson",
    customerEmail: "lisa.a@example.com",
    customerPhone: "(512) 555-0106",
    customerInitials: "LA",
    service: "Solar Maintenance",
    description: "Annual solar panel cleaning and inspection for existing 15-panel system.",
    address: "987 Cedar Ln, Austin, TX 78706",
    status: "cancelled" as RequestStatus,
    priority: "low" as const,
    assignedTech: null,
    techId: null,
    estimatedCost: 500,
    createdAt: "2026-02-10",
    scheduledDate: null,
    urgency: "LOW",
  },
]

// ---- QUOTES ----
export const quotes = [
  {
    id: "QUO-001",
    requestId: "REQ-001",
    service: "Solar Panel Installation",
    customer: "John Smith",
    customerInitials: "JS",
    technician: "Mike Wilson",
    techInitials: "MW",
    status: "accepted" as const,
    totalAmount: 15000,
    laborCost: 1000,
    materialsCost: 14000,
    submittedDate: "2026-02-22",
    validUntil: "2026-03-24",
    estimatedDuration: "3-4 days",
    notes: "Includes 20 x 400W monocrystalline panels, inverter, mounting hardware, and full installation. Permits and inspection fees included.",
    breakdown: [
      { item: "Solar Panels (20x 400W)", cost: 8000 },
      { item: "Inverter System", cost: 2500 },
      { item: "Mounting & Racking", cost: 1500 },
      { item: "Wiring & Electrical", cost: 1200 },
      { item: "Permits & Inspection", cost: 800 },
      { item: "Labor", cost: 1000 },
    ],
  },
  {
    id: "QUO-002",
    requestId: "REQ-004",
    service: "EV Charger Installation",
    customer: "Emily Chen",
    customerInitials: "EC",
    technician: "Tom Harris",
    techInitials: "TH",
    status: "pending" as const,
    totalAmount: 2200,
    laborCost: 200,
    materialsCost: 2000,
    submittedDate: "2026-02-27",
    validUntil: "2026-03-29",
    estimatedDuration: "4-6 hours",
    notes: "Level 2 ChargePoint Home Flex charger. Includes dedicated 50-amp circuit from panel.",
    breakdown: [
      { item: "Level 2 EV Charger Unit", cost: 900 },
      { item: "240V Circuit Installation", cost: 600 },
      { item: "Wiring & Conduit", cost: 350 },
      { item: "Permits", cost: 150 },
      { item: "Labor", cost: 200 },
    ],
  },
  {
    id: "QUO-003",
    requestId: "REQ-006",
    service: "Solar Maintenance",
    customer: "Lisa Anderson",
    customerInitials: "LA",
    technician: "Mike Wilson",
    techInitials: "MW",
    status: "expired" as const,
    totalAmount: 500,
    laborCost: 100,
    materialsCost: 400,
    submittedDate: "2026-02-12",
    validUntil: "2026-02-26",
    estimatedDuration: "2-3 hours",
    notes: "Annual cleaning and inspection for existing 15-panel system. Includes performance report.",
    breakdown: [
      { item: "Panel Cleaning (15 panels)", cost: 200 },
      { item: "System Inspection", cost: 150 },
      { item: "Performance Report", cost: 50 },
      { item: "Labor", cost: 100 },
    ],
  },
]

// ---- PAYMENTS ----
export const payments = [
  {
    id: "PAY-001",
    requestId: "REQ-003",
    customer: "Robert Davis",
    customerEmail: "robert.d@example.com",
    service: "Emergency Repair",
    amount: 850,
    status: "completed" as const,
    method: "Credit Card",
    cardLast4: "4242",
    date: "2026-02-16",
  },
  {
    id: "PAY-002",
    requestId: "REQ-001",
    customer: "John Smith",
    customerEmail: "john.smith@example.com",
    service: "Solar Panel Installation",
    amount: 7500,
    status: "completed" as const,
    method: "Bank Transfer",
    cardLast4: null as string | null,
    date: "2026-02-22",
    note: "50% deposit",
  },
  {
    id: "PAY-003",
    requestId: "REQ-002",
    customer: "Sarah Johnson",
    customerEmail: "sarah.j@example.com",
    service: "Electrical Panel Upgrade",
    amount: 1750,
    status: "completed" as const,
    method: "Credit Card",
    cardLast4: "8888",
    date: "2026-02-24",
    note: "50% deposit",
  },
  {
    id: "PAY-004",
    requestId: "REQ-005",
    customer: "Michael Brown",
    customerEmail: "michael.b@example.com",
    service: "Residential Wiring",
    amount: 2250,
    status: "pending" as const,
    method: "Credit Card",
    cardLast4: "1234",
    date: "2026-02-28",
    note: "50% deposit",
  },
]

// ---- TECHNICIAN JOBS (from Mike Wilson's perspective) ----
export const technicianJobs = [
  {
    id: "JOB-001",
    requestId: "REQ-001",
    customer: "John Smith",
    customerInitials: "JS",
    service: "Solar Panel Installation",
    address: "123 Main St, Austin, TX 78701",
    scheduledDate: "2026-03-05",
    status: "in_progress" as const,
    priority: "high" as const,
    estimatedPay: 3500,
    estimatedDuration: "3-4 days",
  },
  {
    id: "JOB-002",
    requestId: "REQ-002",
    customer: "Sarah Johnson",
    customerInitials: "SJ",
    service: "Electrical Panel Upgrade",
    address: "456 Oak Ave, Austin, TX 78702",
    scheduledDate: "2026-03-08",
    status: "scheduled" as const,
    priority: "medium" as const,
    estimatedPay: 900,
    estimatedDuration: "4-5 hours",
  },
]

// Jobs completed by the logged-in technician (Mike Wilson)
export const completedJobs = [
  {
    id: "JOB-003",
    requestId: "REQ-007",
    customer: "Patricia Lewis",
    customerInitials: "PL",
    service: "Solar Maintenance",
    address: "555 River Rd, Austin, TX 78707",
    completedDate: "2026-02-20",
    status: "completed" as const,
    payment: 380,
  },
]

// Jobs available for bidding
export const availableJobs = [
  {
    id: "AVAIL-001",
    service: "EV Charger Installation",
    customer: "William Garcia",
    address: "444 Birch St, Austin, TX 78708",
    postedDate: "2026-02-28",
    estimatedPay: 800,
    urgency: "low" as const,
    distance: "4.2 mi",
  },
  {
    id: "AVAIL-002",
    service: "Panel Upgrade",
    customer: "Daniel Thompson",
    address: "987 Cedar Ln, Pflugerville, TX 78660",
    postedDate: "2026-02-27",
    estimatedPay: 1500,
    urgency: "medium" as const,
    distance: "8.5 mi",
  },
  {
    id: "AVAIL-003",
    service: "Solar Inspection",
    customer: "Nancy Clark",
    address: "321 Oak Dr, Round Rock, TX 78664",
    postedDate: "2026-02-28",
    estimatedPay: 250,
    urgency: "low" as const,
    distance: "2.1 mi",
  },
]

// ---- TECHNICIAN EARNINGS (Mike Wilson) ----
export const techEarningsMonthly = [
  { month: "Sep", amount: 5200 },
  { month: "Oct", amount: 6800 },
  { month: "Nov", amount: 5900 },
  { month: "Dec", amount: 4500 },
  { month: "Jan", amount: 7200 },
  { month: "Feb", amount: 6400 },
]

export const techRecentPayments = [
  { id: "PAY-101", date: "2026-02-26", service: "Emergency Repair", customer: "Robert Davis", amount: 650, status: "paid" as const },
  { id: "PAY-100", date: "2026-02-22", service: "Solar Maintenance", customer: "Patricia Lewis", amount: 380, status: "paid" as const },
  { id: "PAY-099", date: "2026-02-18", service: "Panel Inspection", customer: "Jennifer Wilson", amount: 250, status: "paid" as const },
  { id: "PAY-098", date: "2026-02-15", service: "EV Charger Install", customer: "Michael Brown", amount: 920, status: "paid" as const },
  { id: "PAY-097", date: "2026-02-10", service: "Residential Wiring", customer: "Sarah Johnson", amount: 1100, status: "paid" as const },
]

export const techPendingPayments = [
  { id: "INV-012", service: "Solar Panel Installation (in progress)", customer: "John Smith", amount: 3500, dueDate: "Upon completion" },
  { id: "INV-013", service: "Electrical Panel Upgrade", customer: "Sarah Johnson", amount: 900, dueDate: "2026-03-12" },
]

// ---- CONVERSATIONS / MESSAGES ----
export const conversations = [
  {
    id: "conv-1",
    name: "John Smith",
    role: "Customer",
    initials: "JS",
    lastMessage: "Thanks for the update, looking forward to the installation!",
    time: "11:00 AM",
    unread: 1,
    online: true,
    requestId: "REQ-001",
  },
  {
    id: "conv-2",
    name: "Emily Chen",
    role: "Customer",
    initials: "EC",
    lastMessage: "Can we reschedule to the afternoon?",
    time: "9:30 AM",
    unread: 1,
    online: false,
    requestId: "REQ-004",
  },
  {
    id: "conv-3",
    name: "OMIS Dispatch",
    role: "Operations",
    initials: "OD",
    lastMessage: "New job request in your area - EV charger installation",
    time: "Yesterday",
    unread: 0,
    online: true,
    requestId: null,
  },
  {
    id: "conv-4",
    name: "Michael Brown",
    role: "Customer",
    initials: "MB",
    lastMessage: "What type of wire do you recommend for the garage?",
    time: "Feb 26",
    unread: 0,
    online: false,
    requestId: "REQ-005",
  },
]

// ---- ADMIN DASHBOARD DATA ----
export const adminDashboardStats = {
  totalRequests: 6,
  activeRequests: 3,
  pendingQuotes: 1,
  totalRevenue: 12350,
  totalTechnicians: technicians.length,
  completedThisMonth: 1,
}

export const adminRecentRequests = serviceRequests.slice(0, 5)

export const adminTopTechnicians = [
  { name: "Mike Wilson", jobs: 156, rating: 4.9, earnings: 145000, specialty: "Solar Installation" },
  { name: "Sarah Williams", jobs: 21, rating: 4.8, earnings: 28000, specialty: "Panel Upgrades" },
  { name: "James Brown", jobs: 89, rating: 4.7, earnings: 98000, specialty: "Emergency Repairs" },
]

export const adminPendingApplications = [
  { name: "David Chen", specialty: "Solar Installation", experience: "3 years", appliedDate: "2026-02-25" },
  { name: "Maria Garcia", specialty: "Residential Wiring", experience: "5 years", appliedDate: "2026-02-26" },
]

// ---- CUSTOMER DASHBOARD (from John Smith's perspective) ----
export const customerDashboardStats = {
  activeRequests: 2,
  pendingQuotes: 1,
  completedJobs: 0,
  totalSpent: 9250,
}

// Recent requests for the logged-in customer (John Smith)
export const customerRecentRequests = serviceRequests.filter(
  (r) => r.customerId === "CUS-001"
)

// ---- HELPER: get customer by ID ----
export function getCustomerById(id: string) {
  return customers.find((c) => c.id === id)
}

// ---- HELPER: get technician by ID ----
export function getTechnicianById(id: string) {
  return technicians.find((t) => t.id === id)
}

// ---- HELPER: get request by ID ----
export function getRequestById(id: string) {
  return serviceRequests.find((r) => r.id === id)
}

// ---- ADMIN APPLICATIONS DATA ----
export const mockApplications = [
  {
    id: "APP-001",
    name: "Alex Thompson",
    email: "alex.t@email.com",
    phone: "(555) 111-2222",
    location: "Austin, TX",
    appliedDate: "2026-02-28",
    status: "pending",
    position: "Solar Installation Technician",
    experience: "5 years",
    certifications: ["NABCEP PV Associate", "OSHA 10"],
    education: "Associate Degree in Electrical Technology",
    resume: "alex_thompson_resume.pdf",
    coverLetter: true,
  },
  {
    id: "APP-002",
    name: "Maria Rodriguez",
    email: "maria.r@email.com",
    phone: "(555) 222-3333",
    location: "Round Rock, TX",
    appliedDate: "2026-02-27",
    status: "reviewing",
    position: "Electrician",
    experience: "8 years",
    certifications: ["Master Electrician License", "OSHA 30"],
    education: "Bachelor's in Electrical Engineering",
    resume: "maria_rodriguez_resume.pdf",
    coverLetter: true,
  },
  {
    id: "APP-003",
    name: "Kevin Chen",
    email: "kevin.c@email.com",
    phone: "(555) 333-4444",
    location: "Cedar Park, TX",
    appliedDate: "2026-02-26",
    status: "interview",
    position: "EV Charger Specialist",
    experience: "3 years",
    certifications: ["EVITP Certified", "Journeyman Electrician"],
    education: "Trade School Certificate",
    resume: "kevin_chen_resume.pdf",
    coverLetter: false,
  },
  {
    id: "APP-004",
    name: "Sarah Williams",
    email: "sarah.w@email.com",
    phone: "(555) 444-5555",
    location: "Pflugerville, TX",
    appliedDate: "2026-02-25",
    status: "approved",
    position: "Solar Installation Technician",
    experience: "4 years",
    certifications: ["NABCEP", "First Aid/CPR"],
    education: "High School Diploma + Apprenticeship",
    resume: "sarah_williams_resume.pdf",
    coverLetter: true,
  },
  {
    id: "APP-005",
    name: "David Park",
    email: "david.p@email.com",
    phone: "(555) 555-6666",
    location: "Georgetown, TX",
    appliedDate: "2026-02-24",
    status: "rejected",
    position: "Electrician",
    experience: "1 year",
    certifications: [],
    education: "Trade School (In Progress)",
    resume: "david_park_resume.pdf",
    coverLetter: false,
  },
]

// ---- ADMIN REPORTS DATA ----
export const revenueData = [
  { month: "Jan", revenue: 45000, jobs: 28 },
  { month: "Feb", revenue: 52000, jobs: 32 },
  { month: "Mar", revenue: 48000, jobs: 30 },
  { month: "Apr", revenue: 61000, jobs: 38 },
  { month: "May", revenue: 55000, jobs: 35 },
  { month: "Jun", revenue: 67000, jobs: 42 },
]

export const serviceBreakdown = [
  { name: "Solar Installation", revenue: 125000, percentage: 38, color: "bg-amber-500" },
  { name: "Electrical Panels", revenue: 85000, percentage: 26, color: "bg-blue-500" },
  { name: "EV Chargers", revenue: 52000, percentage: 16, color: "bg-green-500" },
  { name: "Emergency Repairs", revenue: 35000, percentage: 11, color: "bg-red-500" },
  { name: "Other Services", revenue: 31000, percentage: 9, color: "bg-purple-500" },
]

export const reportTopTechnicians = [
  { name: "Mike Wilson", jobs: 45, revenue: 68500, rating: 4.9 },
  { name: "James Brown", jobs: 42, revenue: 63200, rating: 4.8 },
  { name: "Carlos Martinez", jobs: 38, revenue: 57800, rating: 5.0 },
  { name: "Tom Harris", jobs: 35, revenue: 48900, rating: 4.7 },
]

export const recentReports = [
  { name: "Monthly Revenue Report", date: "Feb 2026", type: "Financial" },
  { name: "Technician Performance", date: "Feb 2026", type: "HR" },
  { name: "Customer Satisfaction", date: "Feb 2026", type: "Quality" },
  { name: "Service Analytics", date: "Jan 2026", type: "Operations" },
]

// ---- TECHNICIAN MESSAGES DATA ----
export const technicianConversations = [
  {
    id: "conv-1",
    name: "John Smith",
    role: "Customer",
    initials: "JS",
    lastMessage: "Thanks for the update, looking forward to the installation!",
    time: "11:00 AM",
    unread: 1,
    online: true,
    requestId: "REQ-001",
  },
  {
    id: "conv-2",
    name: "Patricia Lewis",
    role: "Customer",
    initials: "PL",
    lastMessage: "Can we reschedule to the afternoon?",
    time: "9:30 AM",
    unread: 1,
    online: false,
    requestId: "REQ-007",
  },
  {
    id: "conv-3",
    name: "OMIS Dispatch",
    role: "Operations",
    initials: "OD",
    lastMessage: "New job request in your area - EV charger installation",
    time: "Yesterday",
    unread: 0,
    online: true,
    requestId: null,
  },
  {
    id: "conv-4",
    name: "Nancy Clark",
    role: "Customer",
    initials: "NC",
    lastMessage: "What type of wire do you recommend for the garage?",
    time: "Feb 26",
    unread: 0,
    online: false,
    requestId: "REQ-009",
  },
]

export const technicianMessages = [
  {
    id: 1,
    sender: "John Smith",
    isMe: false,
    message: "Hi Mike! Just wanted to check on the status of the permit application.",
    time: "10:00 AM",
    status: "read",
  },
  {
    id: 2,
    sender: "Me",
    isMe: true,
    message: "Hi John! Good news - the permits were approved yesterday. We're all set for the March 5th installation date.",
    time: "10:15 AM",
    status: "read",
  },
  {
    id: 3,
    sender: "John Smith",
    isMe: false,
    message: "That's great! Do I need to prepare anything before you arrive?",
    time: "10:20 AM",
    status: "read",
  },
  {
    id: 4,
    sender: "Me",
    isMe: true,
    message: "Just make sure the garage and driveway are accessible for our truck and equipment. We'll arrive around 8 AM and the first day is mostly setting up scaffolding and the mounting rails.",
    time: "10:30 AM",
    status: "read",
  },
  {
    id: 5,
    sender: "John Smith",
    isMe: false,
    message: "Thanks for the update, looking forward to the installation!",
    time: "11:00 AM",
    status: "delivered",
  },
]
